"""O QUE ESTE PROJETO VAI PROCESSAR. E O UNICO ARQUIVO QUE VOCE EDITA ANTES DE RODAR.

DIVISAO DE RESPONSABILIDADE ENTRE OS DOIS ARQUIVOS DE CONFIGURACAO:

    config.py      ->  ONDE AS COISAS ESTAO. CAMINHO DO BANCO, PASTAS, CHAVE E MODELO
                       DA IA, NOMES DE COLUNA DO RENAEST. MUDA QUANDO A INFRAESTRUTURA
                       MUDA, O QUE E RARO.

    parametros.py  ->  O QUE VOCE QUER PROCESSAR. MUNICIPIO, ANO, TAMANHO DE LOTE,
                       APARENCIA DO MAPA. MUDA A CADA EXECUCAO.

POR QUE ISTO EXISTE
-------------------
ANTES, CADA NOTEBOOK TRAZIA ESSES VALORES NA PROPRIA PRIMEIRA CELULA. O MUNICIPIO
APARECIA **DUAS VEZES, EM FORMAS DIFERENTES**: COMO `CIDADE` E `ESTADO` NO NOTEBOOK 02,
PARA CONSULTAR O OPENSTREETMAP, E COMO `CODIGO_IBGE` NOS NOTEBOOKS 03, 04 E 05, PARA
RECORTAR OS ACIDENTES. NADA GARANTIA QUE AS DUAS FALASSEM DA MESMA CIDADE.

QUANDO ELAS DIVERGEM, O ERRO E SILENCIOSO E CARO: OS ACIDENTES DE UMA CIDADE SAO
ASSOCIADOS AS RUAS DE OUTRA, APROVEITANDO NOMES QUE COINCIDEM, E O RESULTADO SAI MARCADO
COMO 'ok'. NADA AVISA.

AGORA O MUNICIPIO E ESCOLHIDO **UMA VEZ**, PELO CODIGO DO IBGE, E AS OUTRAS FORMAS SAO
DERIVADAS DELE. NAO HA COMO DIVERGIR.
"""

# ---------------------------------------------------------------------------
# MUNICIPIO
# ---------------------------------------------------------------------------

# CADA ENTRADA LIGA O CODIGO DO IBGE, QUE RECORTA OS ACIDENTES, AO NOME DA CIDADE,
# QUE E O QUE O OPENSTREETMAP ENTENDE.
#
# PARA ACRESCENTAR UM MUNICIPIO: PEGUE O CODIGO NA ETAPA 8 DO NOTEBOOK 01, QUE LISTA
# OS RECORTES DISPONIVEIS COM A CONTAGEM DE ACIDENTES DE CADA UM. CONFIRA QUE O CODIGO
# E A CIDADE SAO REALMENTE O MESMO LUGAR ANTES DE GRAVAR AQUI -- UM PAR ERRADO NESTA
# TABELA E EXATAMENTE O ERRO SILENCIOSO QUE ESTE ARQUIVO EXISTE PARA EVITAR.
MUNICIPIOS = {
    "5201405": {"cidade": "Aparecida de Goiânia", "estado": "Goias"},
    "3106200": {"cidade": "Belo Horizonte", "estado": "Minas Gerais"},
    "5300108": {"cidade": "Brasília", "estado": "Distrito Federal"},
    "3550308": {"cidade": "São Paulo", "estado": "São Paulo"},
}

# O MUNICIPIO ATIVO. E ESTA LINHA QUE VOCE TROCA PARA MUDAR DE CIDADE.
CODIGO_IBGE = "5201405"

# FALHA AGORA, COM MENSAGEM CLARA, EM VEZ DE ESTOURAR UM KeyError NO MEIO DE UM NOTEBOOK.
if CODIGO_IBGE not in MUNICIPIOS:
    raise ValueError(
        f"CODIGO_IBGE {CODIGO_IBGE!r} NAO ESTA EM MUNICIPIOS.\n"
        f"CONHECIDOS: {', '.join(sorted(MUNICIPIOS))}\n"
        "ACRESCENTE O MUNICIPIO NO DICIONARIO ACIMA."
    )

# AS DUAS FORMAS DERIVADAS. O NOTEBOOK 02 USA ESTAS; O 03, O 04 E O 05 USAM O CODIGO.
CIDADE = MUNICIPIOS[CODIGO_IBGE]["cidade"]
ESTADO = MUNICIPIOS[CODIGO_IBGE]["estado"]


# ---------------------------------------------------------------------------
# RECORTE DE TEMPO
# ---------------------------------------------------------------------------

# ANO PROCESSADO PELOS NOTEBOOKS 03 E 04. UM ANO POR EXECUCAO.
ANO = 2024

# ANO DESENHADO PELO NOTEBOOK 05. `None` SOMA TODOS OS ANOS JA ASSOCIADOS, O QUE DA UM
# GRADIENTE MELHOR NO MAPA. UM NUMERO RESTRINGE A UM ANO.
#
# E DELIBERADO QUE SEJA UMA VARIAVEL SEPARADA DE `ANO`: O 03 E O 04 PROCESSAM UM ANO DE
# CADA VEZ, ENQUANTO O MAPA COSTUMA QUERER TUDO O QUE JA FOI PROCESSADO.
ANO_MAPA = None


# ---------------------------------------------------------------------------
# NOTEBOOK 01 -- INGESTAO DO RENAEST
# ---------------------------------------------------------------------------

# ENDPOINT DO PORTAL QUE LISTA OS RECURSOS DISPONIVEIS DO RENAEST.
URL_PACOTE = "https://dados.transportes.gov.br/api/3/action/package_show?id=renaest"

# QUANTAS LINHAS LER POR VEZ AO CARREGAR CSV GRANDES. EVITA ESTOURO DE MEMORIA.
TAMANHO_CHUNK = 50_000

# SO OS ARQUIVOS CUJO NOME COMECA COM ALGUM DESTES PREFIXOS SERAO CARREGADOS.
# PARA CARREGAR TODOS OS CSV DA EXTRACAO, TROQUE POR None.
PREFIXOS_ARQUIVOS_PROCESSADOS = ("Acidentes",)

# SE True, REAPROVEITA O ZIP JA BAIXADO EM VEZ DE BAIXAR DE NOVO.
USAR_ARQUIVOS_LOCAIS_SE_EXISTIREM = True


# ---------------------------------------------------------------------------
# NOTEBOOK 02 -- MALHA VIARIA
# ---------------------------------------------------------------------------

# DISTANCIA MAXIMA PARA CONSIDERAR QUE DOIS TRECHOS COM O MESMO NOME SAO A MESMA VIA.
DISTANCIA_AGRUPAMENTO_METROS = 100

# RAIO DO BUFFER FINAL DA VIA, USADO COMO AREA DE INFLUENCIA AO REDOR DA LINHA.
RAIO_BUFFER_VIA_METROS = 150

# RAIO USADO SOMENTE NO CALCULO QUE ESTIMA O EIXO CENTRAL EM POSSIVEIS PISTAS DUPLAS.
RAIO_BUFFER_PISTA_DUPLA_METROS = 50

# LIMITE DA RAZAO PARA CLASSIFICAR UMA VIA COMO POSSIVEL PISTA DUPLA.
LIMITE_RAZAO_PISTA_DUPLA = 1.4

# FRACAO MINIMA DE MAO UNICA PARA UMA VIA PODER SER PISTA DUPLA.
LIMITE_FRACAO_ONEWAY = 0.2

# COMPRIMENTO MINIMO, EM METROS, PARA CONFIAR NA FORMULA DO EIXO.
COMPRIMENTO_MINIMO_PISTA_DUPLA = 400

# CRS METRICO INICIAL. A ETAPA 3 DO NOTEBOOK 02 AJUSTA PARA A ZONA UTM DA CIDADE.
CRS_METRICO = 31982


# ---------------------------------------------------------------------------
# NOTEBOOKS 03 E 04 -- CHAMADAS A IA
# ---------------------------------------------------------------------------

# QUANTOS PARES DISTINTOS DE ENDERECO POR CHAMADA, NA REVISAO (NOTEBOOK 03).
TAMANHO_LOTE_REVISAO = 30

# QUANTOS PARES, COM SUAS CANDIDATAS, POR CHAMADA NA ASSOCIACAO (NOTEBOOK 04).
# E MENOR QUE O DA REVISAO PORQUE CADA ITEM AQUI CARREGA UMA LISTA DE CANDIDATAS.
TAMANHO_LOTE_ASSOCIACAO = 20

# QUANTAS VIAS CANDIDATAS A BUSCA PROPOE PARA CADA ENDERECO (NOTEBOOK 04).
# A INSTRUCAO ENVIADA A IA USA ESTE MESMO NUMERO, ENTAO OS DOIS NUNCA DIVERGEM.
TOP_N = 6

# QUANTAS CHAMADAS PODEM ESTAR EM VOO AO MESMO TEMPO NA REVISAO.
MAX_CONCORRENTES = 4

# SEGUNDOS MINIMOS ENTRE O INICIO DE UMA CHAMADA E O INICIO DA SEGUINTE.
# ERA 6 PARA CABER NA COTA GRATUITA DO GEMINI. O DEEPSEEK NAO IMPOE ESSE RITMO.
# SE APARECER ERRO DE COTA, AUMENTE.
DELAY_ENTRE_LOTES = 1
PAUSA_ENTRE_CHAMADAS = 1

# QUANTAS VEZES TENTAR UM LOTE ANTES DE DEIXAR PARA A PROXIMA EXECUCAO.
TENTATIVAS = 3

# TETO DE TOKENS DA RESPOSTA. O MODO JSON DA API TRUNCA SEM AVISAR SE ESTE VALOR FOR
# CURTO, E RESPOSTA TRUNCADA FAZ O LOTE FALHAR DE PROPOSITO.
MAX_TOKENS_RESPOSTA = 8192

# SE O MODELO RACIOCINA ANTES DE RESPONDER. VEM DESLIGADO: EM TESTE COM OS MESMOS
# ENDERECOS E COM OS MESMOS CASOS DIFICEIS DE ASSOCIACAO, A SAIDA FOI IDENTICA COM E SEM
# RACIOCINIO, GASTANDO CERCA DE DEZ VEZES MAIS TOKENS NA REVISAO E VINTE NA ASSOCIACAO.
PENSAMENTO_LIGADO = False

# `extra_body` LEVA PARAMETROS QUE SAO DO DEEPSEEK E NAO EXISTEM NA API DA OPENAI.
CORPO_EXTRA = {} if PENSAMENTO_LIGADO else {"thinking": {"type": "disabled"}}


# ---------------------------------------------------------------------------
# NOTEBOOK 05 -- MAPA DE CALOR
# ---------------------------------------------------------------------------

# EXPOENTE DA ESCALA DE COR. 0.5 E A RAIZ QUADRADA, O EQUILIBRIO ESCOLHIDO NA ETAPA 3 DO
# NOTEBOOK 05: SEPARA BEM AS PIORES VIAS SEM APAGAR O PELOTAO DO MEIO.
# MAIS PERTO DE 1.0 SEPARA MAIS O TOPO E APAGA MAIS O MEIO; MAIS PERTO DE 0.2 FAZ O
# CONTRARIO. NAO USE 0.
EXPOENTE_ESCALA = 0.5

# ESPESSURA DA LINHA, EM PIXELS, DA VIA COM MENOS ACIDENTES A COM MAIS.
LARGURA_MINIMA = 1.5
LARGURA_MAXIMA = 9

# TRANSPARENCIA DA VIA COM MENOS ACIDENTES. A COM MAIS E SEMPRE OPACA.
OPACIDADE_MINIMA = 0.35

# LIGA A CAMADA CINZA COM AS VIAS QUE NAO RECEBERAM NENHUM ACIDENTE.
MOSTRAR_VIAS_SEM_ACIDENTE = False

# NOME DO ARQUIVO HTML GRAVADO PELO NOTEBOOK 05, DENTRO DE data/mapas.
NOME_ARQUIVO_MAPA = "mapa_calor_vias.html"


def resumo():
    """IMPRIME O QUE SERA PROCESSADO. USADO NA PRIMEIRA CELULA DOS NOTEBOOKS."""
    print(f"MUNICIPIO         : {CIDADE} / {ESTADO}  (IBGE {CODIGO_IBGE})")
    print(f"ANO (03 E 04)     : {ANO}")
    print(f"ANO (MAPA)        : {ANO_MAPA if ANO_MAPA is not None else 'TODOS OS ASSOCIADOS'}")
    print(f"RACIOCINIO DA IA  : {'LIGADO' if PENSAMENTO_LIGADO else 'DESLIGADO'}")
